export const ACTION_TYPES = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  CREATE_HR_REQUEST: "CREATE_HR_REQUEST",
  CREATE_EMPLOYEE: "CREATE_EMPLOYEE",
  APPROVE_HR_REQUEST: "APPROVE_HR_REQUEST",
  REJECT_HR_REQUEST: "REJECT_HR_REQUEST",
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
  UPDATE_SALARY: "UPDATE_SALARY",
  CREATE_DEPARTMENT: "CREATE_DEPARTMENT",
  UPDATE_DEPARTMENT: "UPDATE_DEPARTMENT",
  DELETE_DEPARTMENT: "DELETE_DEPARTMENT",
};
